// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "forsakenanton@gmail.com",
                            EstimatedIncome = 1000m,
                            Name = "Anton",
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "example@gmail.com",
                            EstimatedIncome = 3000m,
                            Name = "ExampleName",
                            YearsOfExperience = 5
                        });
                });

            modelBuilder.Entity("Core.Entities.PersonalProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectStage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("PersonalProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeveloperId = 1,
                            ProjectName = "OnlineStore",
                            ProjectStage = 0
                        },
                        new
                        {
                            Id = 2,
                            DeveloperId = 1,
                            ProjectName = "SpecificationPattern",
                            ProjectStage = 0
                        },
                        new
                        {
                            Id = 3,
                            DeveloperId = 2,
                            ProjectName = "ExampleProject1",
                            ProjectStage = 0
                        },
                        new
                        {
                            Id = 4,
                            DeveloperId = 2,
                            ProjectName = "ExampleProject2",
                            ProjectStage = 1
                        },
                        new
                        {
                            Id = 5,
                            DeveloperId = 2,
                            ProjectName = "ExampleProject3",
                            ProjectStage = 1
                        },
                        new
                        {
                            Id = 6,
                            DeveloperId = 2,
                            ProjectName = "ExampleProject4",
                            ProjectStage = 2
                        });
                });

            modelBuilder.Entity("Core.Entities.PersonalProject", b =>
                {
                    b.HasOne("Core.Entities.Developer", "Developer")
                        .WithMany("PersonalProjects")
                        .HasForeignKey("DeveloperId");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("Core.Entities.Developer", b =>
                {
                    b.Navigation("PersonalProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
